CREATE TABLE [DOMAIN].[CRRNCY] (    [MEMBER_ID] NVARCHAR(50) NOT NULL,
    [DESCRIPTION] NVARCHAR(250),
    [MEMBER_TECHNICAL_ID] NVARCHAR(100), 
    CONSTRAINT [PK_CRRNCY] PRIMARY KEY ([MEMBER_ID]))
