CREATE VIEW TRANSFORM.CRDT_CRD_DBT_CNVNNC_CRDT_E
AS
SELECT ANNLSD_AGRD_RT = 0,
       CNNCTD_FCTRNG_ID = NULL,
       IS_CRDT_LN_OTHR_RV_CRDT = 0,
       DT_END_INTRST_ONLY =  CAST(NULL AS DATETIME2),
       DT_NXT_INTRST_RT_RST =  CAST(NULL AS DATETIME2),
       INTRST_RT_CP = NULL,
       INTRST_RT_FLR = NULL,
       INTRST_RT_RST_FRQNCY = NULL,
       INTRST_RT_SPRD = NULL,
       PRPS = CASE
                  WHEN IS_DBT_FNNCNG = 'T' THEN
                      5
                  ELSE
                      11
              END,
       PYMNT_FRQNCY = 4,
       RFRNC_RT = 0,
       RPYMNT_RGHTS = 2,
       IS_RVLVNG_LN = 0,
       SBRDNTD_DBT = 2,
       SYNDCTD_CNTRCT_ID = NULL,
       TYP_AMRTSTN = 4,
       TYP_INTRST_RT = 0,
       TYP_INSTRMNT = 40,
	   OTSTNDNG_NMNL_AMNT,
       PRCNTG_TRNSFRRD,
       PRDNTL_PRTFL,
       PRJCT_FNNC_LN,
       PRVSNS_OFF_BLNC_SHT,
       RCRS,
       RLTNSHP_SCRTSTN_CRDT_TRNSFR,
       SCRTSTN_TRNSFR_ID,
       SRC_ENCMBRNC,
       INSTRMNT_UNQ_ID,
       ACCMLTD_CHNGS_FV_CR,
       ACCMLTD_IMPRMNT,
       ACCMLTD_WRTFFS,
       ACCNTNG_CLSSFCTN,
       ACCRD_INTRST,
       APPRCH_CRDT_QLTY_STTS,
       ARRRS,
       CMLTV_RCVRS_SNC_DFLT,
       CMMTMNT_INCPTN,
       CNTRCT_ID,
       CRDT_QLTY_STTS,
       CRRNCY_DNMNTN,
       CRRYNG_AMNT,
       DT_DFLT_STTS,
       DT_FRBRNC_STTS,
       DT_INCPTN,
       DT_LGL_FNL_MTRTY,
       DT_PRFRMNG_STTS,
       DT_PST_D,
       DT_STTLMNT,
       FDCRY,
       FRBRNC_STTS,
       FV,
       FV_CHNG_CR_BFR_PRCHS,
       FV_CHNG_HDG_ACCNTNG,
       GRSS_CRRYNG_AMNT_E_INTRST,
       IMPRMNT_ASSSSMNT_MTHD,
       IMPRMNT_STTS,
       INSTRMNT_ID,
       IS_DBT_FNNCNG,
       IS_RTL_EXPSR,
       IS_SRVCD_OBSRVD_AGNT,
       OBSRVD_AGNT_INTRNL_ID,
       OFF_BLNC_SHT_AMNT
FROM INPUT.CRDT_CRD_DBT_CNVNNC_CRDT
GO
EXEC sp_addextendedproperty @name = N'TRANSFORMATION',
                            @value = N'D_IMPLCT_CRDT_CRD_DBT_CNVNNC_CRDT',
                            @level0type = N'SCHEMA',
                            @level0name = N'TRANSFORM',
                            @level1type = N'VIEW',
                            @level1name = N'CRDT_CRD_DBT_CNVNNC_CRDT_E',
                            @level2type = NULL,
                            @level2name = NULL;